default_language_version:
    python: python3
repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.15
    hooks:
    -   id: ruff
        args:
          - --fix
        files: ^(src|scripts)/
    -   id: ruff-format