
environments:
  dev:
    strict_path_adjustment_policy: true
    workflows:
      - name: "wf_template_dev"
        job_clusters:
          - job_cluster_key: "cluster_dev"
            new_cluster:
              cluster_source: "JOB"
              spark_version: "13.2.x-scala2.12"
              node_type_id: "c5d.4xlarge"
              policy_id: "9C6308F7030079E8"
              num_workers: 1
              aws_attributes:
                first_on_demand: 1
                availability: "SPOT_WITH_FALLBACK"
                zone_id: "auto"
                spot_bid_price_percent: 100
                ebs_volume_count: 0     

        tasks:

          - task_key: "set_parameters"
            job_cluster_key: "cluster_dev"
            max_retries: 0
            spark_python_task:
              python_file: "file://tasks/main.py"
              parameters: ["--task=set_parameters","--env=dev","--input=test","--output=test1"]
          
          - task_key: "task1"
            job_cluster_key: "cluster_dev"
            max_retries: 0
            spark_python_task:
              python_file: "file://tasks/main.py"
              parameters: ["--task=task1"]
            depends_on:
            - task_key: "set_parameters"                   

          - task_key: "task2"
            job_cluster_key: "cluster_dev"
            max_retries: 0
            spark_python_task:
              python_file: "file://tasks/main.py"
              parameters: ["--task=task2"]
            depends_on:
            - task_key: "task1"

  prod:
    strict_path_adjustment_policy: true
    workflows:
      - name: "wf_template_prod"
        job_clusters:
          - job_cluster_key: "cluster_prod"
            new_cluster:
              cluster_source: "JOB"
              spark_version: "13.2.x-scala2.12"
              node_type_id: "c5d.4xlarge"
              policy_id: "9C63D8C50400EF74"
              num_workers: 1
              aws_attributes:
                first_on_demand: 1
                availability: "SPOT_WITH_FALLBACK"
                zone_id: "auto"
                spot_bid_price_percent: 100
                ebs_volume_count: 0     
        tasks:

          - task_key: "set_parameters"
            job_cluster_key: "cluster_prod"
            max_retries: 0
            spark_python_task:
              python_file: "file://tasks/main.py"
              parameters: ["--task=set_parameters","--env=prod","--input=202309-1"]
          
          - task_key: "task1"
            job_cluster_key: "cluster_prod"
            max_retries: 0
            spark_python_task:
              python_file: "file://tasks/main.py"
              parameters: ["--task=task1"]
            depends_on:
            - task_key: "set_parameters"

          - task_key: "task2"
            job_cluster_key: "cluster_prod"
            max_retries: 0
            spark_python_task:
              python_file: "file://tasks/main.py"
              parameters: ["--task=task2"]
            depends_on:
            - task_key: "task1"