name: CI pipeline

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*' # this tag type is used for release pipelines

jobs:
  ci-pipeline:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN:  ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v2

      # - name: pip
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt

      - name: pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install packages
      #    pipenv run pytest tests/
          pipenv run curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
          pipenv run databricks --version
          pipenv run databricks workspace list /
          pipenv run databricks bundle deploy --target dev
          pipenv run databricks bundle run default_python
          
      # - name: Run unit tests
      #   run: |
      #     echo "Launching unit tests"
      #     pytest tests/

      # - name: Jobless deployment (files only upload)
      #   run: |
      #     curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
      #     databricks --version
      #     databricks workspace list /
          
      #- name: Run the job in a jobless fashion
      #  run: |
      #    pipenv run databricks bundle run
