name: CI pipeline

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*' # this tag type is used for release pipelines

jobs:
  ci-pipeline:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN:  ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install pip
        run: |
          python -m pip install --upgrade pip
          
      - name: Install dependencies and project
        run: |
          pip install packages
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      #- name: Run unit tests
      #  run: |
      #    echo "Launching unit tests"
      #    pytest tests/

      - name: Jobless deployment (files only upload)
        run: |
          databricks --version
          databricks workspace list /

      - name: Run the job in a jobless fashion
        run: |
          pipenv run databricks bundle run


