name: CI pipeline

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*' # this tag type is used for release pipelines

jobs:
  ci-pipeline:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN:  ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          make install

      - name: Install Databricks CLI
        run: |
          pipenv run curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
          pipenv run databricks --version

      - name: Package and Deployment
        run: |
          make deploy-dev

      - name: Run job
        run: |
          make run-dev

      - name: Run
        run: |
          make deploy-ci
