name: CI pipeline

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*' # this tag type is used for release pipelines
    paths-ignore:
      - 'README.md'
      - 'docs/**'

jobs:
  ci-pipeline:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN:  ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'        

      - name: Install dependencies
        run: |
          make install

      - name: Run pytest and coverage (unit tests)
        run: |
          make test

      - name: Install Databricks CLI
        uses: databricks/setup-cli@main

      - name: Deploy on staging
        run: |
          make deploy-serverless env=staging

      - name: Run on staging (integration tests)
        run: |
          make run env=staging

      - name: Deploy on prod
        run: |
          make deploy-serverless env=prod
